-- Database schema for WebPortal application
-- Generated by ChatGPT
 
CREATE TABLE accounts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    account_number VARCHAR(50) NOT NULL,
    customer_id BIGINT NOT NULL,
    balance DECIMAL(15, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
);
 
CREATE TABLE customers (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    address VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
 
CREATE TABLE movements (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    amount DECIMAL(15, 2) NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customer_movement FOREIGN KEY (customer_id) REFERENCES customers(id)
);
 
 
INSERT INTO customers (name, email, address) VALUES
('John Doe', 'john.doe@example.com', '1234 Elm St, Springfield, IL'),
('Jane Smith', 'jane.smith@example.com', '5678 Oak St, Springfield, IL');
 
INSERT INTO accounts (account_number, customer_id, balance) VALUES
('ACC12345', 1, 1000.00),
('ACC12346', 2, 1500.00);
 
INSERT INTO movements (customer_id, type, amount, date) VALUES
(1, 'deposit', 200.00, '2025-01-06 12:00:00'),
(1, 'withdrawal', 50.00, '2025-01-06 13:00:00'),
(2, 'deposit', 300.00, '2025-01-06 14:00:00');
