version: '3.8'
services:
  webportal:
    build: .
    ports:
      - "8080:80"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/webportal
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webportal
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
